# Generated by Django 3.1 on 2020-08-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='HomeTestModel',
        ),
    ]
