# Generated by Django 3.1.1 on 2020-09-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments of the company'},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'short_name')},
        ),
    ]
