# Generated by Django 3.1.1 on 2020-09-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20200910_0310'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Employee Skills',
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-first_name', 'last_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees of the company'},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('first_name', 'department')},
        ),
    ]
