# Generated by Django 3.1.1 on 2020-09-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20200913_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skill',
            field=models.ManyToManyField(to='person.Skill'),
        ),
    ]
